name: Backend deployment
on:
  push:
    branches: main

jobs:
  Deploy:
    runs-on: self-hosted
    env:
      PASSWORD: ${{secrets.SSH_PASSWORD}}

    steps:
      - name: Remove old deployment
        run: |
          echo ${{env.PASSWORD}} | sudo -S -e lsof -t -i:8085 >> pid.tmp
          echo ${{env.PASSWORD}} | sudo -S -e kill -9 $(echo pid.tmp)

      - name: Change directory to server
        run: cd ~/wce-resource-tracker/server

      - name: Deploy backend
        run: echo ${{env.PASSWORD}} | sudo -S nohup node index.js > log.out 2>&1 &
